/*
 * This file was automatically generated by EvoSuite
 * Sun Mar 19 20:46:06 GMT 2017
 */

package dominion;

import org.junit.Test;
import static org.junit.Assert.*;
import dominion.Cards;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class Cards_ESTest extends Cards_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test00()  throws Throwable  {
      Cards cards0 = new Cards((String) null, (-953), (-953), (String) null, (Boolean) null);
      cards0.getType();
      assertEquals(-953, cards0.getCost());
  }

  @Test(timeout = 4000)
  public void test01()  throws Throwable  {
      Cards cards0 = new Cards("Z0DOJRmL", (-49), (-49), "Z0DOJRmL", (Boolean) null);
      cards0.getType();
      assertEquals(-49, cards0.getCost());
  }

  @Test(timeout = 4000)
  public void test02()  throws Throwable  {
      Cards cards0 = new Cards("Z0DOJRmL", (-49), (-49), "Z0DOJRmL", (Boolean) null);
      cards0.addEmbargo();
      Boolean boolean0 = cards0.getToken();
      assertTrue(boolean0);
      assertEquals(-49, cards0.getCost());
  }

  @Test(timeout = 4000)
  public void test03()  throws Throwable  {
      Boolean boolean0 = Boolean.FALSE;
      Cards cards0 = new Cards("#=G$84Pm6nzf", (-41), (-41), "#=G$84Pm6nzf", boolean0);
      cards0.getToken();
      assertEquals(-41, cards0.getCost());
  }

  @Test(timeout = 4000)
  public void test04()  throws Throwable  {
      Cards cards0 = new Cards("Z0DOJRmL", (-49), (-49), "Z0DOJRmL", (Boolean) null);
      cards0.getName();
      assertEquals(-49, cards0.getCost());
  }

  @Test(timeout = 4000)
  public void test05()  throws Throwable  {
      Cards cards0 = new Cards("", 0, 0, "", (Boolean) null);
      cards0.getName();
      assertEquals(0, cards0.getCost());
  }

  @Test(timeout = 4000)
  public void test06()  throws Throwable  {
      Boolean boolean0 = Boolean.FALSE;
      Cards cards0 = new Cards("wk@R6Ijfv", 0, 0, "wk@R6Ijfv", boolean0);
      int int0 = cards0.getCost();
      assertEquals(0, int0);
  }

  @Test(timeout = 4000)
  public void test07()  throws Throwable  {
      Cards cards0 = new Cards("Z0DOJRmL", (-49), (-49), "Z0DOJRmL", (Boolean) null);
      int int0 = cards0.getCost();
      assertEquals((-49), int0);
  }

  @Test(timeout = 4000)
  public void test08()  throws Throwable  {
      Cards cards0 = new Cards((String) null, (-1510), (-1510), (String) null, (Boolean) null);
      cards0.getName();
      assertEquals(-1510, cards0.getCost());
  }

  @Test(timeout = 4000)
  public void test09()  throws Throwable  {
      Cards cards0 = new Cards("[", 1, 1, "[", (Boolean) null);
      int int0 = cards0.getCost();
      assertEquals(1, int0);
  }

  @Test(timeout = 4000)
  public void test10()  throws Throwable  {
      Cards cards0 = new Cards("", 2085, 2085, "", (Boolean) null);
      cards0.getType();
      assertEquals(2085, cards0.getCost());
  }

  @Test(timeout = 4000)
  public void test11()  throws Throwable  {
      Cards cards0 = new Cards("nF", (-540), (-540), "nF", (Boolean) null);
      cards0.getToken();
      assertEquals(-540, cards0.getCost());
  }

  @Test(timeout = 4000)
  public void test12()  throws Throwable  {
      Cards cards0 = new Cards("Z0DOJRmL", (-49), (-49), "Z0DOJRmL", (Boolean) null);
      String string0 = cards0.toString();
      assertEquals("Z0DOJRmL -49 -49 Z0DOJRmL null", string0);
  }
}
